# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero GPL v3 or later

version: "3"

networks:
  ssl-reverse-proxy:
    external: yes

services:
  wnpp-debian-net:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      # KEEP IN SYNC with container "cron" below
      WDN_ALLOWED_HOSTS: ${WDN_ALLOWED_HOSTS}
      WDN_DEBUG: ${WDN_DEBUG}
      WDN_MYSQL_HOST: mysql
      WDN_MYSQL_NAME: ${WDN_MYSQL_NAME:?}
      WDN_MYSQL_PASSWORD: ${WDN_MYSQL_PASSWORD:?}
      WDN_MYSQL_PORT: ${WDN_MYSQL_PORT:?}
      WDN_MYSQL_USER: ${WDN_MYSQL_USER:?}
      WDN_SECRET_KEY: ${WDN_SECRET_KEY:?}
      WDN_SENTRY_DSN: ${WDN_SENTRY_DSN}
      # KEEP IN SYNC with container "cron" below
    ports:
      - 127.0.0.1:51080:51080
    networks:
      - default
      - ssl-reverse-proxy
    user: 1001:1001
    cap_drop:
      - ALL
    restart: unless-stopped
    tty: true

  cron:
    depends_on:
      - mysql
    image: ${COMPOSE_PROJECT_NAME:-wnppdebiannet}_wnpp-debian-net
    command: ["sh", "-c", "supercronic -sentry-dsn \"${WDN_SENTRY_DSN}\" ~/crontab"]
    environment:
      # KEEP IN SYNC with container "django" above
      WDN_ALLOWED_HOSTS: ${WDN_ALLOWED_HOSTS}
      WDN_DEBUG: ${WDN_DEBUG}
      WDN_MYSQL_HOST: mysql
      WDN_MYSQL_NAME: ${WDN_MYSQL_NAME:?}
      WDN_MYSQL_PASSWORD: ${WDN_MYSQL_PASSWORD:?}
      WDN_MYSQL_PORT: ${WDN_MYSQL_PORT:?}
      WDN_MYSQL_USER: ${WDN_MYSQL_USER:?}
      WDN_SECRET_KEY: ${WDN_SECRET_KEY:?}
      WDN_SENTRY_DSN: ${WDN_SENTRY_DSN}
      # KEEP IN SYNC with container "django" above
    networks:
      - default
    user: 1001:1001
    cap_drop:
      - ALL
    restart: unless-stopped
    tty: true

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${WDN_MYSQL_PASSWORD:?}
      MYSQL_USER: ${WDN_MYSQL_USER:?}
      MYSQL_PASSWORD: ${WDN_MYSQL_PASSWORD:?}
      MYSQL_DATABASE: ${WDN_MYSQL_NAME:?}
    volumes:
      - ~/wnpp-debian-net/var-lib-mysql:/var/lib/mysql
    restart: unless-stopped
