# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero GPL v3 or later

version: "3"

networks:
  ssl-reverse-proxy:
    external: yes

services:
  wnpp-debian-net:
    depends_on:
      - mysql
    build: ./
    ports:
      - 127.0.0.1:51080:80
    networks:
      - default
      - ssl-reverse-proxy
    volumes:
      - .:/var/www/localhost/htdocs/
    restart: unless-stopped

  django:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      WDN_ALLOWED_HOSTS: ${WDN_ALLOWED_HOSTS}
      WDN_DEBUG: ${WDN_DEBUG}
      WDN_MYSQL_HOST: mysql
      WDN_MYSQL_NAME: ${WDN_MYSQL_NAME:?}
      WDN_MYSQL_PASSWORD: ${WDN_MYSQL_PASSWORD:?}
      WDN_MYSQL_PORT: ${WDN_MYSQL_PORT:?}
      WDN_MYSQL_USER: ${WDN_MYSQL_USER:?}
      WDN_SECRET_KEY: ${WDN_SECRET_KEY:?}
    ports:
      - 127.0.0.1:52080:52080
    networks:
      - default
      - ssl-reverse-proxy
    user: 1001:1001
    cap_drop:
      - ALL
    restart: unless-stopped
    tty: true

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${WDN_MYSQL_PASSWORD:?}
      MYSQL_USER: ${WDN_MYSQL_USER:?}
      MYSQL_PASSWORD: ${WDN_MYSQL_PASSWORD:?}
      MYSQL_DATABASE: ${WDN_MYSQL_NAME:?}
    volumes:
      - ./tables/table_structures.sql:/docker-entrypoint-initdb.d/schema.sql
      - ~/wnpp-debian-net/var-lib-mysql:/var/lib/mysql
    restart: unless-stopped

  cron_sync_list:
    depends_on:
      - wnpp-debian-net
    image: inutano/wget
    command: ["sh", "-c", "sleep 3 ; while :; do wget -O- http://wnpp-debian-net/cron_sync_list.php5 ; sleep 55 ; done"]
    restart: unless-stopped

  cron_sync_popcon:
    depends_on:
      - wnpp-debian-net
    image: inutano/wget
    command: ["sh", "-c", "sleep 2m ; while :; do wget -O- http://wnpp-debian-net/cron_sync_popcon.php5 ; sleep 12h ; done"]
    restart: unless-stopped
